---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SendSi.
--- DateTime: 2022/8/27 15:54
---

local ProxyDialogTipModule = {}
local UIConfig = require("Core.UIConfig")
local UIMgr = require("Core.UIMgr")
local TipTab=require("Tables.TipConfig")
local TipsManager=require("UI.DialogTip.TipsManager")



--ProxyDialogTip:OpenDialogTip2View("我是提示", "我的提示内容是圆明园", "查看武将", function()    loginfo("left")end, "战法点转化", function()    loggZSX("right")end)
-- 两个按钮   默认左边=取消,右边=确认
function ProxyDialogTipModule:OpenDialogTip2View(title, content, leftTxt, leftAction, rigthTxt, rightAction, closeInRightAction, contentTitle)
    local uiset = UIConfig.DialogTip2View
    UIMgr:OpenWindow(uiset, function(view)
        view:SetData(title, content, leftTxt, leftAction, rigthTxt, rightAction, closeInRightAction, contentTitle)
    end)
end


function ProxyDialogTipModule:CloseViewDialogTip2()
    UIMgr:CloseWindow(UIConfig.DialogTip2View)
end


function ProxyDialogTipModule:OpenToastTipView()
    UIMgr:OpenWindow(UIConfig.ToastTipView)
end

-- 飘字
function ProxyDialogTipModule:AddToastTip(tipTxt, ...)
    local args
    if select("#", ...) > 0 then
        args = { ... }
    end

    TipsManager:SaveTipText(tipTxt, args)
end
-- 飘字 tipId
function ProxyDialogTipModule:AddToastTipById(tipId, ...)
    local config = TipTab[tipId]
    if config then
        self:AddToastTip(config.content, ...)
    else
        logerror("导表并无此id :", tipId)
    end
end

return ProxyDialogTipModule