---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SendSi.
--- DateTime: 2022/8/27 15:54
---

local ProxyDialogTipModule = {}
local UIConfig = require("Core.UIConfig")
local UIMgr = require("Core.UIMgr")


-- 两个按钮   默认左边=取消,右边=确认
function ProxyDialogTipModule:OpenDialogTip2View(title, content, leftTxt, leftAction, rigthTxt, rightAction, closeInRightAction, contentTitle)
    local uiset = UIConfig.DialogTip2View
    UIMgr:OpenWindow(uiset, function(view)
        view:SetData(title, content, leftTxt, leftAction, rigthTxt, rightAction, closeInRightAction, contentTitle)
    end)
end

--ProxyDialogTip:OpenDialogTip2View("我是提示", "我的提示内容是圆明园", "查看武将", function()    loginfo("left")end, "战法点转化", function()    loggZSX("right")end)
function ProxyDialogTipModule:CloseViewDialogTip2()
    UIMgr:CloseWindow(UIConfig.DialogTip2View)
end

--[[function ProxyEmojiModule:CloseLoginMain()
    local uiset = UIConfig.LoginMainView
    UIMgr:OpenWindow(uiset, function(uiWin)
        uiWin:SetData("我的emoji")
    end)
end]]

return ProxyDialogTipModule