---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SendSi.
--- DateTime: 2022/8/21 21:28
---

local FunctionsEles = {}

local mTitleClick = {
    ["部队"] = function()
        loggZSX("点了部队")
    end,
    ["邮件"] = function()
        loggZSXError("邮件")
    end,
    ["背包"] = function()
        require("UI.Bag.ProxyBagModule"):OpenBagMainView()
    end,
    ["联盟"] = function()
    end,
    ["英雄"] = function()
    end,
}

function FunctionsEles:Init(rootUI)
    if rootUI then
        self.uiComs = require('ToolGen.03_main.functionsEles'):OnConstruct(rootUI.m_functionsEles)

        self.uiComs.m_btnList.onClickItem:Add(function(context)
            local fun = mTitleClick[context.data.title]
            if fun then
                fun()
            end
        end)

        self.uiComs.m_cutBtn.onClick:Add(function()
            logerror("212")
        end)
    end
end

function FunctionsEles:Dispose()

end

return FunctionsEles