---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SendSi.
--- DateTime: 2022/8/16 22:57
---

local UIWindow = require('Core.UIWindow')
local MainCenterView = fgui.window_class(UIWindow)
local GlobalEvent = require("Core.GlobalEvent")
local EventName = require("Core.EventName")

function MainCenterView:LoadComponent()
    self.uiComs = require('ToolGen.03_main.MainCenterView'):OnConstruct(self.contentPane)

    require("UI.MainCenter.FunctionsEles"):Init(self.uiComs)
end

function MainCenterView:AddBindGlobalEvent()
    local eventData = {
        { EventName.BagUpdate, function(cfgId, strV)
            loggZSXError(strV)
            loggZSXError(cfgId)
        end }
    }
    return eventData
end

function MainCenterView:SetData(str)
    loggZSXWarning(str)
end

function MainCenterView:OnHide()
    UIWindow.OnHide(self)
end

function MainCenterView:OnShown()
    UIWindow.OnShown(self)
end

return MainCenterView
