---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SendSi.
--- DateTime: 2022/8/16 22:57
---

local UIWindow = require('Core.UIWindow')
local MainCenterView = fgui.window_class(UIWindow)
local GlobalEvent = require("Core.GlobalEvent")
local EventName = require("Core.EventName")

function MainCenterView:LoadComponent()
    loggZSX("进来这里了")
    self.uiComs = require('ToolGen.03_main.MainCenterView'):OnConstruct(self.contentPane)

end

local mEventUIds

local function tEventTest(data, value)
    loggZSXWarning(data.key)
    loggZSXWarning(value)
end
local function tEventClick()
    loggZSXWarning("onClick")
end

function MainCenterView:BindRegisterEvent()
    --self.closeBtn.onClick:Add(function()
    --    self:CloseWindow()--父类
    --end)
    --
    --self.uiComs.m_btn1.onClick:Add(function()
    --    GlobalEvent:Fire(EventName.TestEvent, { key = "a", value = true }, "参数我")
    --end)
    --self.uiComs.m_btn2.onClick:Add(function()
    --    GlobalEvent:Fire(EventName.TestOnClick)
    --end)
    --
    --mEventUIds = {
    --    GlobalEvent:AddListener(EventName.TestEvent, tEventTest),
    --    GlobalEvent:AddListener(EventName.TestOnClick, tEventClick)
    --}
end

function MainCenterView:SetData(str)
    loggZSXWarning(str)
end

function MainCenterView:OnHide()
    UIWindow.OnHide(self)
    --if mEventUIds and #mEventUIds > 0 then
    --    for i = 1, #mEventUIds do
    --        GlobalEvent:RemoveListener(mEventUIds[i])
    --    end
    --    mEventUIds = nil
    --end
end

function MainCenterView:OnShown()
    UIWindow.OnShown(self)
end

return MainCenterView
