//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TestLoaderWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("TestLoader");
		L.RegFunction("Test", Test);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Test(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			TestLoader.Test(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

